---
version: "3"
services:
  employees:
    build:
      dockerfile: Dockerfile.dev
      context: ${BASE_DIRECTORY:-../..}/app/backend/employees-service
    image: employees-dev:latests
    stop_signal: SIGINT
    ports:
      - published: 3000
        target: 3000
    volumes:
      - ${BASE_DIRECTORY:-../..}/app/backend/employees-service/app:/home/node/app
      - /home/node/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: 0.0.0.0
      DB_HOSTNAME: db_test
      MYSQL_DATABASE: employees
      MYSQL_USER: enroute
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
        test: ["CMD", "curl", "-I", "-f", "http://localhost:3000/monitoring/livenessCheck"]
        timeout: 5s
        retries: 10
