---
version: "3"
networks:
  enroute:
    name: enroute

services:
  db_test:
    extends:
      file: services/db.yaml
      service: db_test
    networks:
      - enroute
  employees:
    extends:
      file: services/employees.yaml
      service: employees
    networks:
      - enroute
  employees_front:
    extends:
      file: services/employees-front.yaml
      service: employees_front
    networks:
      - enroute

